openapi: 3.0.0
info:
  title: Player API
  version: 1.0.0
paths:
  /api/players:
    get:
      summary: Get all players
      responses:
        '200':
          description: A list of players
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PlayerDto'
  /api/player/{id}:
    get:
      summary: Get player by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A player
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlayerDto'
        '404':
          description: Player not found
    put:
      summary: Update player by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlayerDto'
      responses:
        '200':
          description: Updated player
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlayerDto'
        '404':
          description: Player not found
    delete:
      summary: Delete player by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Player deleted
        '404':
          description: Player not found
  /api/player:
    post:
      summary: Create a new player
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlayerDto'
      responses:
        '201':
          description: Created player
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlayerDto'
components:
  schemas:
    PlayerDto:
      type: object
      properties:
        id:
          type: integer
        firstName:
          type: string
        lastName:
          type: string
